spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-combaict-dev  

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-combaict-test  




